name: 📦 Release Workflow

on:
  release:
    types: [created]

jobs:
  release:
    name: 🚀 Release ${{ matrix.target }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            archive: zip
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            archive: zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - name: 📥 Compiling
        run: cargo build --release --target ${{ matrix.target }}
        env:
          CARGO_TARGET_DIR: target/${{ matrix.target }}

      - name: 📦 Create Archive
        run: |
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.archive }}" == "zip" ]]; then
            zip -r ${{ matrix.target }}.zip *
          else
            tar czvf ${{ matrix.target }}.tar.gz *
          fi

      - name: 📤 Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.target }}.${{ matrix.archive }}
